# Generated by Django 2.2.6 on 2019-10-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=13)),
                ('date_of_employment', models.DateField(auto_now_add=True)),
                ('job_profile', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
