# Generated by Django 2.2.6 on 2019-10-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
        migrations.RenameModel(
            old_name='StaffDetails',
            new_name='StaffDetail',
        ),
    ]
