# Generated by Django 2.2.6 on 2019-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20191029_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('no_of_staff', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('dealer_name', models.CharField(max_length=200)),
                ('dealer_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
