# Generated by Django 2.2.6 on 2019-11-03 14:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20191103_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='contact',
            field=phone_field.models.PhoneField(help_text='Contact Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='no_of_staff',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='contact',
            field=phone_field.models.PhoneField(help_text='Contact Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dealer_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
