# Generated by Django 2.2.6 on 2019-11-03 14:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=phone_field.models.PhoneField(help_text='Contact Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='item_purchased',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_items',
            field=models.PositiveIntegerField(),
        ),
    ]
